title: Dingbang Xie's Homepage
page-top-title: Dingbang Xie
top-section-bg-text: Clinical medicine
home-subtitle: Dingbang Xie&ensp;|&ensp;谢定邦
copyright-text: '&copy; Dingbang Xie 2023-2026. All Rights Reserved.'
